spring:
    datasource:
        url: ${DB_URL}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbs: 
                    lab:
                        non_contextual_creation: true
        hibernate:
            ddl-auto: none
        generate-ddl: false
    mail:
        host: ${MAIL_HOST}
        port: ${MAIL_PORT}
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail: 
                smtp:
                    auth: true
                    starttls:
                        enable: true

springdoc:
    swagger-ui:
        enabled: true
        tagSorter: alpha
        operationsSorter: method
        path: /api/v1/api-docs

com:
    unper:
        samper: 
            domain: samper-api-6bf01e4f0b51.herokuapp.com
            version: 1.0.0
            build: 001
            credit-minutes: 800
            token-expiration-ms: 180000 
            otp-expiration-ms: 1800000 
            security: 
                jwt: 
                    secret: ${JWT_SECRET}
                    access-token-expiration-ms: 900000
                    refresh-token-expiration-ms: 7776000000

external-api:
    faceplusplus:
        base-url: ${FPP_BASE_URL}
        api-key: ${FPP_API_KEY}
        api-secret: ${FPP_SECRET_KEY}
        tomeout: 60000
        end-point:
            CREATE_FACESET: /facepp/v3/faceset/create
            ADD_FACE_FACESET: /facepp/v3/faceset/addface
            UPDATE_FACESET: /facepp/v3/faceset/update
            DELETE_FACESET: /facepp/v3/faceset/delete
            REMMOVE_FACESET: /facepp/v3/faceset/removeface
            GET_DETAIL_FACESET: /facepp/v3/faceset/getdetail
            ADD_USER_ID_FACE: /facepp/v3/face/setuserid
            GET_DETAIL_FACE: /facepp/v3/face/getdetail
            ANALYZE_FACE: /facepp/v3/face/analyze
            FACE_COMPARE: /facepp/v3/compare
            FACE_DETECT: /facepp/v3/detect
    cloudinary:
        cloud-name: ${CDN_CLOUD_NAME}
        api-key: ${CDN_API_KEY}
        api-secret: ${CDN_API_SECRET}
